#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent — Spec 001: Init Glitter Tattoo Project
# This script initializes the development environment for the Next.js SSG site

set -e

echo "========================================"
echo "Glitter Tattoo — Dev Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo -e "${CYAN}Checking prerequisites...${NC}"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed. Please install Node.js 18+ first.${NC}"
    exit 1
fi
NODE_VERSION=$(node -v)
echo -e "${GREEN}Node.js: $NODE_VERSION${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed.${NC}"
    exit 1
fi
NPM_VERSION=$(npm -v)
echo -e "${GREEN}npm: $NPM_VERSION${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo -e "${CYAN}Installing dependencies...${NC}"

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo "Running npm install..."
    npm install
else
    echo -e "${YELLOW}node_modules already exists, skipping install${NC}"
fi

# ============================================
# VERIFY PROJECT CONFIGURATION
# ============================================

echo ""
echo -e "${CYAN}Verifying project configuration...${NC}"

# Check critical files
REQUIRED_FILES=(
    "package.json"
    "next.config.ts"
    "tsconfig.json"
    "postcss.config.mjs"
)

ALL_FOUND=true
for file in "${REQUIRED_FILES[@]}"; do
    if [ -f "$file" ]; then
        echo -e "  ${GREEN}✓${NC} $file"
    else
        echo -e "  ${RED}✗${NC} $file (missing)"
        ALL_FOUND=false
    fi
done

if [ "$ALL_FOUND" = false ]; then
    echo ""
    echo -e "${YELLOW}Some config files are missing. Run subtask-1-1 (project scaffolding) first.${NC}"
    exit 1
fi

# ============================================
# START NEXT.JS DEV SERVER
# ============================================

echo ""
echo -e "${CYAN}Starting Next.js development server...${NC}"

npm run dev &
DEV_PID=$!

wait_for_service 3000 "Next.js Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo -e "  Next.js Dev:  ${CYAN}http://localhost:3000${NC}"
echo ""
echo "Pages (default locale - Thai):"
echo -e "  Homepage:     ${CYAN}http://localhost:3000/th/${NC}"
echo -e "  About:        ${CYAN}http://localhost:3000/th/about/${NC}"
echo -e "  Services:     ${CYAN}http://localhost:3000/th/services/${NC}"
echo -e "  Gallery:      ${CYAN}http://localhost:3000/th/gallery/${NC}"
echo -e "  Contact:      ${CYAN}http://localhost:3000/th/contact/${NC}"
echo ""
echo "Other Locales:"
echo -e "  English:      ${CYAN}http://localhost:3000/en/${NC}"
echo -e "  Chinese:      ${CYAN}http://localhost:3000/zh/${NC}"
echo ""
echo "Commands:"
echo "  npm run dev           — Start dev server"
echo "  npm run build         — Build static export to /out"
echo "  npm run lint          — Run ESLint"
echo "  npm test              — Run tests"
echo "  npx tsx scripts/scrape.ts — Run content scraper"
echo ""
echo -e "${YELLOW}Press Ctrl+C to stop the dev server${NC}"
echo ""

# Wait for the dev server process
wait $DEV_PID
