/**
 * Mapping of old (legacy) URL paths to new URL paths.
 * Used by the catch-all route app/[locale]/[...rest]/page.tsx
 * to redirect visitors from old URLs to the correct new pages.
 *
 * Keys are old paths (without locale prefix).
 * Values are new paths (without locale prefix).
 *
 * Auto-generated by scripts/generate-redirects.ts
 */
export const redirectMap: Record<string, string> = {
  '/2015/index.html': '/',
  '/about_us_en.html': '/about',
  '/about_us_th.html': '/about',
  '/contact_us_en.php': '/contact',
  '/contact_us_th.php': '/contact',
  '/home_en.html': '/',
  '/home.html': '/',
};
